/**
 * Auth constants that have to agree with the Supabase project.
 *
 * ── OTP_LENGTH IS HALF A SETTING ──────────────────────────────────────
 *
 * This number does not decide anything on its own. The code is generated by
 * GoTrue, and how many digits it puts in the email is a PROJECT setting:
 *
 *   Dashboard → Authentication → Sign In / Providers → Email → Email OTP Length
 *   (self-hosted: GOTRUE_MAILER_OTP_LENGTH; local: [auth.email] otp_length)
 *
 * All this constant does is tell the app how many boxes to draw and when a
 * code is complete. If the two disagree the flow is broken in a way that looks
 * like nothing in particular: the project was set to 8, the app drew 6 boxes,
 * and every owner who tried to confirm their email typed the first six digits
 * of an eight-digit code and was told their code was wrong. Nothing logged an
 * error, because nothing was wrong from either side's point of view.
 *
 * So: change one, change the other. The value in force is recorded in
 * docs/SECURITY.md alongside the rate limits, for the same reason.
 *
 * ── WHY 6 AND NOT FEWER ───────────────────────────────────────────────
 *
 * Because 6 is the floor. GoTrue accepts an OTP length between 6 and 10 and
 * refuses anything outside it, so a 5-digit code is not available at any
 * price — not a default we picked, a constraint of the auth provider.
 *
 * 6 is also the number people expect from every other code they have ever
 * been emailed, and the one password managers and iOS/Android autofill are
 * tuned to recognise. Longer is not meaningfully safer here: the codes expire
 * in an hour and Supabase rate-limits verification attempts per IP (the
 * numbers are in docs/SECURITY.md), so guessing is bounded by the server, not
 * by the digit count. The 8 this project was briefly set to bought nothing and
 * cost two extra boxes to type one-handed.
 */
export const OTP_LENGTH = 6;
