/**
 * The Android home-screen widget: one tap starts the seizure timer.
 *
 * ── WHY THE WIDGET IS A CONFIG PLUGIN AND NOT FILES IN /android ───────
 *
 * `/android` is gitignored in this project — it is prebuild OUTPUT, rebuilt
 * from app.config.ts by `npx expo prebuild --clean`. An AppWidgetProvider
 * dropped into it by hand survives exactly until the next prebuild, and then
 * disappears from every home screen at the following release with nothing in
 * the diff to explain it. So the widget's Kotlin, its layout and its manifest
 * entry are all generated here, on every prebuild, from this one file.
 *
 * The iOS half of the same feature lives in targets/seizure/ and is linked by
 * @bacons/apple-targets for the same reason. Both point at the same URL.
 *
 * ── WHAT IT GENERATES ─────────────────────────────────────────────────
 *
 *   java/<package>/SeizureWidgetProvider.kt   the provider — one PendingIntent
 *   res/layout/pawtrack_seizure_widget.xml    the tile
 *   res/xml/pawtrack_seizure_widget_info.xml  size, preview, update policy
 *   res/drawable/pawtrack_widget_*.xml        background, record ring
 *   res/drawable-v31/…_background.xml         the same tile, system radius
 *   res/values/pawtrack_widget_strings.xml    gallery label and description
 *   AndroidManifest.xml                       the <receiver>
 *
 * Every generated file is prefixed `pawtrack_widget_` / `pawtrack_seizure_`
 * and lives in its own strings file rather than being merged into the
 * template's `strings.xml`. Resource names are a flat namespace shared with
 * every library in the build, and this plugin runs last — a generic name like
 * `widget_background` would silently overwrite, or be overwritten by, whatever
 * else claimed it.
 *
 * ── THE URL ───────────────────────────────────────────────────────────
 *
 * `pawtrack://seizure/start` — scheme from app.config.ts, path from
 * app/seizure/start.tsx. MainActivity already carries an intent-filter for the
 * scheme (Expo generates it from `scheme`) and is `launchMode="singleTask"`,
 * so a tap resumes the existing task through onNewIntent rather than stacking
 * a second copy of the app on top of itself.
 *
 * It must NOT point at /seizure/live: that screen displays a timer, it does
 * not start one. See the comment at the top of app/seizure/start.tsx.
 */

const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/** The route the widget opens. Keep in step with targets/seizure/index.swift. */
const WIDGET_URL = 'pawtrack://seizure/start';

/** Unqualified class name; the package comes from `android.package`. */
const PROVIDER_CLASS = 'SeizureWidgetProvider';

/* ------------------------------------------------------------------ */
/* Generated sources                                                   */
/* ------------------------------------------------------------------ */

const providerKotlin = (packageName) => `package ${packageName}

// GENERATED by plugins/withSeizureWidget.js on every \`expo prebuild\`.
// Edit that file, not this one — this copy is overwritten.

import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.RemoteViews

/**
 * A button, and nothing else.
 *
 * There is no timeline, no state and no periodic update (updatePeriodMillis is
 * 0 in the provider info): the tile draws the same thing forever, so the only
 * work onUpdate does is re-attach the PendingIntent. A widget that asked to be
 * woken would spend battery to change nothing, and — the reason that matters
 * here — could be mid-refresh at the moment someone needs to tap it.
 *
 * It deliberately does not display the elapsed time of a seizure in progress.
 * That would need the app to push a RemoteViews update on every tick, which
 * the system is free to throttle; a timer that is sometimes wrong is worse on
 * this screen than no timer at all. The live screen owns elapsed time.
 */
class ${PROVIDER_CLASS} : AppWidgetProvider() {
    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray,
    ) {
        for (appWidgetId in appWidgetIds) {
            val views = RemoteViews(context.packageName, R.layout.pawtrack_seizure_widget)

            val intent = Intent(Intent.ACTION_VIEW, Uri.parse("${WIDGET_URL}")).apply {
                // Explicitly OUR app. Without this the URL is offered to
                // anything on the device claiming the scheme, and a seizure
                // timer must not be openable in a chooser dialog.
                setPackage(context.packageName)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }

            val pendingIntent = PendingIntent.getActivity(
                context,
                0,
                intent,
                // IMMUTABLE is mandatory from API 31 and correct everywhere:
                // nothing outside the app has any business rewriting where
                // this points. UPDATE_CURRENT keeps one instance rather than
                // accumulating one per widget refresh.
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
            )

            // The whole tile is the target, not just the ring. Someone
            // reaching for this is not aiming carefully.
            views.setOnClickPendingIntent(R.id.pawtrack_widget_root, pendingIntent)

            appWidgetManager.updateAppWidget(appWidgetId, views)
        }
    }
}
`;

const GENERATED_XML_HEADER =
  '<!-- GENERATED by plugins/withSeizureWidget.js. Edit that file, not this one. -->';

const layoutXml = `<?xml version="1.0" encoding="utf-8"?>
${GENERATED_XML_HEADER}
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/pawtrack_widget_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:gravity="center_vertical|start"
    android:background="@drawable/pawtrack_widget_background"
    android:padding="14dp"
    android:contentDescription="@string/pawtrack_seizure_widget_label">

    <!-- A FrameLayout, not a Space, and it is load-bearing: RemoteViews will
         only inflate the view classes marked @RemoteView, and Space and the
         bare View are not among them. Either one throws at inflation time and
         the launcher shows "Problem loading widget" with no other clue.
         The weight pushes the wording to the bottom, so the ring reads as the
         thing you press and the words as its label. -->
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">

        <ImageView
            android:layout_width="42dp"
            android:layout_height="42dp"
            android:layout_gravity="top|start"
            android:src="@drawable/pawtrack_widget_record_ring"
            android:contentDescription="@null" />
    </FrameLayout>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/pawtrack_seizure_widget_title"
        android:textColor="#FFFFFFFF"
        android:textSize="17sp"
        android:textStyle="bold"
        android:maxLines="1" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="@string/pawtrack_seizure_widget_hint"
        android:textColor="#D9FFFFFF"
        android:textSize="12sp"
        android:maxLines="1"
        android:ellipsize="end" />
</LinearLayout>
`;

/**
 * `resizeMode="none"` and a fixed 2x2: the tile is one button, and a stretched
 * button is still one button. `updatePeriodMillis="0"` because nothing on it
 * ever changes — see the provider.
 *
 * targetCellWidth/Height, previewLayout and description are API 31 attributes.
 * Older launchers ignore them and fall back to minWidth/minHeight and
 * previewImage, which is why all of them are present.
 */
const widgetInfoXml = `<?xml version="1.0" encoding="utf-8"?>
${GENERATED_XML_HEADER}
<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android"
    android:minWidth="110dp"
    android:minHeight="110dp"
    android:targetCellWidth="2"
    android:targetCellHeight="2"
    android:updatePeriodMillis="0"
    android:resizeMode="none"
    android:widgetCategory="home_screen"
    android:initialLayout="@layout/pawtrack_seizure_widget"
    android:previewLayout="@layout/pawtrack_seizure_widget"
    android:previewImage="@mipmap/ic_launcher"
    android:description="@string/pawtrack_seizure_widget_description" />
`;

/**
 * The app's seizure red, from src/theme/tokens.ts (colors.red → colors.redDeep).
 * Hardcoded rather than referenced: a widget is drawn by the launcher's
 * process, and the values are duplicated in targets/seizure/expo-target.config.js
 * for the same reason. Change the token, change all three.
 */
const backgroundXml = `<?xml version="1.0" encoding="utf-8"?>
${GENERATED_XML_HEADER}
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:radius="26dp" />
    <gradient
        android:type="linear"
        android:angle="315"
        android:startColor="#D0483F"
        android:endColor="#A93327" />
</shape>
`;

/** The same record ring the app draws in its tab bar: white ring, solid dot. */
const recordRingXml = `<?xml version="1.0" encoding="utf-8"?>
${GENERATED_XML_HEADER}
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="oval">
            <solid android:color="#00000000" />
            <stroke android:width="3dp" android:color="#8CFFFFFF" />
        </shape>
    </item>
    <item
        android:top="7dp"
        android:bottom="7dp"
        android:left="7dp"
        android:right="7dp">
        <shape android:shape="oval">
            <solid android:color="#FFFFFFFF" />
        </shape>
    </item>
</layer-list>
`;

const stringsXml = `<?xml version="1.0" encoding="utf-8"?>
${GENERATED_XML_HEADER}
<resources>
    <!-- Shown under the tile in the launcher's widget picker. Says what it
         does rather than repeating the app name, which the picker already
         groups by. -->
    <string name="pawtrack_seizure_widget_label">Record seizure</string>
    <string name="pawtrack_seizure_widget_description">Starts PawTrack\\'s seizure timer with one tap.</string>
    <string name="pawtrack_seizure_widget_title">Seizure</string>
    <string name="pawtrack_seizure_widget_hint">Tap to start timer</string>
</resources>
`;

/**
 * The same tile, rounded to the launcher's own radius on Android 12+.
 *
 * From API 31 the system gives widgets a device-specific corner radius, and a
 * tile that hardcodes its own sits visibly inside the cut corner. There is a
 * platform dimension for it, but only from 31 — hence two copies of the
 * drawable rather than one: `drawable-v31` reads the system value, plain
 * `drawable` keeps the fixed 26dp for everything older.
 */
const backgroundXmlV31 = backgroundXml.replace(
  'android:radius="26dp"',
  'android:radius="@android:dimen/system_app_widget_background_radius"',
);

/* ------------------------------------------------------------------ */
/* Mods                                                                */
/* ------------------------------------------------------------------ */

/** Every generated file, as a path relative to `android/app/src/main`. */
function generatedFiles(packageName) {
  return {
    [`java/${packageName.split('.').join('/')}/${PROVIDER_CLASS}.kt`]:
      providerKotlin(packageName),
    'res/layout/pawtrack_seizure_widget.xml': layoutXml,
    'res/xml/pawtrack_seizure_widget_info.xml': widgetInfoXml,
    'res/drawable/pawtrack_widget_background.xml': backgroundXml,
    'res/drawable/pawtrack_widget_record_ring.xml': recordRingXml,
    'res/drawable-v31/pawtrack_widget_background.xml': backgroundXmlV31,
    'res/values/pawtrack_widget_strings.xml': stringsXml,
  };
}

const withWidgetSources = (config) =>
  withDangerousMod(config, [
    'android',
    async (config) => {
      const packageName = config.android?.package;
      if (!packageName) {
        // Loud on purpose. Silently skipping would produce a build that works
        // and simply has no widget, with nothing anywhere saying why.
        throw new Error(
          '[withSeizureWidget] android.package is not set in app.config.ts; ' +
            'the widget provider has no package to live in.',
        );
      }

      const main = path.join(
        config.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
      );

      for (const [relative, contents] of Object.entries(generatedFiles(packageName))) {
        const file = path.join(main, relative);
        await fs.promises.mkdir(path.dirname(file), { recursive: true });
        await fs.promises.writeFile(file, contents, 'utf8');
      }

      return config;
    },
  ]);

/**
 * Adds the `<receiver>`.
 *
 * `exported="false"` is correct and is what Android's own widget documentation
 * uses: the APPWIDGET_UPDATE broadcast comes from the system as an explicit
 * intent to this component, so it does not need to be reachable by other apps
 * — and making it reachable would let any app on the device trigger it.
 */
function addReceiver(androidManifest, packageName) {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  const name = `${packageName}.${PROVIDER_CLASS}`;

  application.receiver = application.receiver ?? [];
  // Idempotent: prebuild without --clean re-runs mods over a manifest that may
  // already carry the receiver, and two would be a manifest merger failure.
  application.receiver = application.receiver.filter(
    (receiver) => receiver.$?.['android:name'] !== name,
  );

  application.receiver.push({
    $: {
      'android:name': name,
      'android:exported': 'false',
      'android:label': '@string/pawtrack_seizure_widget_label',
    },
    'intent-filter': [
      {
        action: [
          { $: { 'android:name': 'android.appwidget.action.APPWIDGET_UPDATE' } },
        ],
      },
    ],
    'meta-data': [
      {
        $: {
          'android:name': 'android.appwidget.provider',
          'android:resource': '@xml/pawtrack_seizure_widget_info',
        },
      },
    ],
  });

  return androidManifest;
}

const withWidgetReceiver = (config) =>
  withAndroidManifest(config, (config) => {
    config.modResults = addReceiver(
      config.modResults,
      config.android?.package ?? '',
    );
    return config;
  });

const withSeizureWidget = (config) =>
  withWidgetReceiver(withWidgetSources(config));

module.exports = withSeizureWidget;
/** Exported for the check in scripts/; keep them pure. */
module.exports.addReceiver = addReceiver;
module.exports.generatedFiles = generatedFiles;
module.exports.WIDGET_URL = WIDGET_URL;
