import { Placeholder } from '@/components/Placeholder';

/**
 * SAFETY-CRITICAL SCREEN.
 *
 * Every field here is entered by the owner or their veterinarian. The app must
 * never generate, suggest, autofill or infer any of this content — especially
 * not medication names or doses.
 */
export default function EmergencyPlanScreen() {
  return (
    <Placeholder
      title="Emergency plan"
      summary="Vet contact numbers and the emergency instructions your veterinarian gave you. Nothing on this screen is generated by the app."
      todo={[
        'Primary vet: name, clinic, phone (all optional)',
        'Emergency vet: name, clinic, phone (all optional)',
        'Free-text: when to call, rescue medication, dose/route, max doses, special instructions',
        'Phone fields accept international formats — never reformat or validate to one country',
        'Save via dogRepo.updateDog with vet / emergencyVet / emergencyPlan',
      ]}
    />
  );
}
